# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Temper' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Temper
  pod 'Alamofire'
  pod 'Swinject'
  pod 'RxSwift'
  
  target 'TemperTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
